spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.ewm.stats.avro.UserActionAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.ewm.stats.avro.EventSimilarityAvroSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
