spring:
  cloud:
    gateway:
      routes:
        - id: request-service-events
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests/**
        - id: request-service-users
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: ewm-service
          uri: lb://main-service
          predicates:
            - Path=/**
    loadbalancer:
      cache:
        enabled: false
