spring:
  cloud:
    gateway:
      routes:
        - id: ewm-service
          uri: lb://main-service
          predicates:
            - Path=/**
    loadbalancer:
      cache:
        enabled: false
