server.port=8080
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:service
spring.datasource.username=service
spring.datasource.password=service
spring.datasource.continue-on-error=true
spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
stats-service.url=http://localhost:9090
