server:
  port: 8080

spring:
  application:
    name: ewm-main-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_main_db
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

stats-service:
  url: http://localhost:9090